### ISSUE TITLE
log what is happening (pre start run start post start)

### ISSUE THREAD

**Issue by rcastellotti** [rcastellotti/tinyben#10]

**Comment by rcastellotti** [comment]
we are logging in the base class, we need to implement a way to have meaningful log positions

![image](https://github.com/rcastellotti/tinyben/assets/43064224/077eb620-e430-42e6-916a-4584e8fc7606)

**Comment by fedfontana** [comment]
should also log module name and function name (`%(module)` and `%(funcName)` are valid logging formatter templates, but they do not work: with the current setup they always print `base` and `run`)
